### ISSUE TITLE
PyPI version needs updating

### ISSUE THREAD

**Issue by colsmit** [tjefferies/pymetalog#7]
Had a message from a concerned user: The PyPI version is currently out of sync with Github repo, so when someone tries to use the usage examples available on Github with the PyPI package there are unexpected keyword arguments (`pentalty`, `alpha`) and methods (`.update()`). 

Travis, can you take a look at this? Haven't wrangled PyPI before and I don't want to break anything...

**Comment by tjefferies** [comment]
On it

**Comment by tjefferies** [comment]
Version 0.2 is on pypi now
